# Generated by Django 6.1.1 on 2026-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.CharField(choices=[('Huila', 'huila'), ('Antioquia', 'antioquia'), ('Cundinamarca', 'cundinamarca'), ('Santander', 'santander')], default='huila', max_length=100),
        ),
    ]
